vich_uploader:
    db_driver: orm

    mappings:
        candidat:
            uri_prefix: /uploads/candidats
            upload_destination: '%kernel.project_dir%/public/uploads/candidats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
