<?php

namespace ContainerMESSrNp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zkau2_XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zkau2.x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zkau2.x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminCandidatController::delete' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\AdminCandidatController::edit' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\AdminCandidatController::index' => ['privates', '.service_locator.WEMvFZ1', 'get_ServiceLocator_WEMvFZ1Service', true],
            'App\\Controller\\AdminCandidatController::show' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\CandidatController::index' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminCandidatController:delete' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\AdminCandidatController:edit' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\AdminCandidatController:index' => ['privates', '.service_locator.WEMvFZ1', 'get_ServiceLocator_WEMvFZ1Service', true],
            'App\\Controller\\AdminCandidatController:show' => ['privates', '.service_locator.4XzjmVT', 'get_ServiceLocator_4XzjmVTService', true],
            'App\\Controller\\CandidatController:index' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminCandidatController::delete' => '?',
            'App\\Controller\\AdminCandidatController::edit' => '?',
            'App\\Controller\\AdminCandidatController::index' => '?',
            'App\\Controller\\AdminCandidatController::show' => '?',
            'App\\Controller\\CandidatController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminCandidatController:delete' => '?',
            'App\\Controller\\AdminCandidatController:edit' => '?',
            'App\\Controller\\AdminCandidatController:index' => '?',
            'App\\Controller\\AdminCandidatController:show' => '?',
            'App\\Controller\\CandidatController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
