<?php

namespace ContainerMESSrNp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCollectionConnaissancesInformatiqueTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CollectionConnaissancesInformatiqueType' shared autowired service.
     *
     * @return \App\Form\CollectionConnaissancesInformatiqueType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'CollectionConnaissancesInformatiqueType.php';

        return $container->privates['App\\Form\\CollectionConnaissancesInformatiqueType'] = new \App\Form\CollectionConnaissancesInformatiqueType();
    }
}
