<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXSNxswY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXSNxswY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXSNxswY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXSNxswY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXSNxswY\App_KernelDevDebugContainer([
    'container.build_hash' => 'XSNxswY',
    'container.build_id' => '1d8fa7ed',
    'container.build_time' => 1627553237,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXSNxswY');
